### PR TITLE
Support changing JqGrid default values.

### PR DESCRIPTION
**Pull request by Vampire2008**
Only main change.
Some developers changing default values of JqGrid in JavaScript. 
Example:
```javascript
$.jqgid.default.cmTemplate = { align: 'center' };
```
And if deleloper wants to set aligment in one column to Left, with you library that doesn't work.
I did so that for every option JavaSctipt generetes only if option was setted. I did it for options in ColumnModel (and it dependensies) and JqGridOptions.

The truth is, there are disadvantages:
- If we set Editable, Searchable or Sortable attributes, JavaScript for this options always generates.
- JqGridHelper constructor with multiple parametres generate more redurant JavaScript code. I mark them as Obsolete. And create new constructor with JqGridOption as parameter.
- I changed behavior of JsonReader and ParameterNames. In static fields they uses only for Requests and Responses (global scope). In JqGridOption uses to set different than global values for Grid. And if we change something in JsonReader/ParametersNames in global scope, we need to change default values for JqGrid in JavaScript.

Other changes:
- In JqGridOptions added static field DefaultCompatibilityMode. If we use in whole project only Gurido JqGrid we don't need anymore define Compatibility mode for every grid.
- Seeding ColumnModel now in base JqGridOption class with method SetModel. Generic version of JqGridOption leaved for compatibility.
- For attributes Editable, Searchable removed bool parameter in constructors where we set additional fields. I decided if we sets this parameters, that that field is Editable/Searchable. In other constructors for bool value added default value.
- Added support JetBrains.Annotations.

In the affected files, a refactoting was made:
- Remove unused usings.
- Changed code style to C# 7.2 (without vars).
- Removed redundant code.

It's a minimal pull request, that I can do.

### CODE REVIEW

**Comment by tpeczek** [comment]
This is certainly not a minimal pull request ;). A minimal pull request here would be only the changes required for giving the ability to render the values which are currently considered default and never rendered. All the other changes (so generally all bullet points) are stuff for separated pull requests.

I was able to skim through this (in the context of the business change from the title, I'm skipping all the additional changes from bullet points), so generally:
- There is a lot of changes which break backward compatibility. Every change like that is a potential red flag and it will require separated discussion on why it is needed.
- There is still tons of unjustifed styling changes, at moments it looks like ReSharper has been blindly run against the code with assumption that all the changes it does are for better. As I said previously the current coding style of the project should be maintained. The only styling changes I see valuable are expression-bodied properties, string interpolation and some usages of `nameof` operator.
- I'm against adding `JetBrains.Annotations`, it's an unnecessary third party dependency. This project has a lot more users than developers ;).

If it comes to the business change itself, I don't like the `*Setted` pattern spreading throughout the entire code base. A less invasive change would be to introduce static default options:

```cs
public class JqGridOptions
{
    public static JqGridOptions Default { get; }
}
```

And use them instead of `JqGridOptionsDefaults` in `JqGridHelper` and `JqGridScriptConverter` (the `JqGridOptionsDefaults` would be used to seed that static instance). This way the developer can make the same global change in `JqGridOptions.Default` as in JavaScript.

I'm happy that you are trying to improve this project and I hope that together we will be able to bring some useful changes which you are proposing. But this have to be done in safe and responsible way, so it brings value to whoever might be using this library without bringing issues and problems.

**Comment by Vampire2008** [comment]
In start I was thinking about static property Defaults.
But I not found best the way, how it should work.

First option:
We set in `Global.asax` option and than it applies to all grids.
```csharp
JqGridOption.Defaults.ColumnModelTemplate.Alignment = JqGridAlignments.Center;
```
In `JqGridHelper`:
```csharp
if (columnModel.Alignment != JqGridOption.Defaults.ColumnModelTemplate.Alignment)
    javaScriptBuilder.AppendFormat("align: '{0}', ", columnModel.Alignment.ToString().ToLower());
else if (JqGridOption.Defaults.ColumnModelTemplate.Alignment != JqGridAlignments.Left)
   javaScriptBuilder.AppendFormat("align: '{0}', ", JqGridOption.Defaults.ColumnModelTemplate.Alignment.ToString().ToLower());
```
But this code will be generate `align: center` for all grids and columns.

Second options:
We set in `Global.asax` options and in JavaScript. 'JqGridOptions.Defaults will be used only for synchronize with JavaSctipt code.
`Global.asax`
```csharp
JqGridOption.Defaults.ColumnModelTemplate.Alignment = JqGridAlignments.Center;
```
JS:
```JavaSctipt
$.jgrid.defaults.cmTemplate = { align: 'center' };
```
It will be generate normal code. But it is double work for developers.

And after that I came to `*Setted` pattern. With bool properties was simple. I just made them `Nullable`. But string properties can be `null` initiatly. And I made `*Setted` properties to detect, that they was setted. It be important if developer wants to set `null` to property.

JetBrains.Annotations used in `EditableAttribute` and `SearchableAttribute` on parametres for Action, Controller and Area. Developers, who used ReSharper, can set and check this parameters with Intellisense.
It only file, that compiled into assembly. Not external dependency. I left this in pull request because it used in files, that affect the main change.

About backward compatibility. Sometimes you have to give it up.
I tested changes on you test project from CodePlex. Not many changes to the code need to be made.
I personally have to make a lot of changes to my code to migrate to your library.

**Comment by tpeczek** [comment]
The only way I see this functionality going in is the second option you have described (this is the one I've intended in my comment).

This project is over 7 years old and haven't brought a noticable breaking change in over 3 years. I cannot stress how much I value backward compatibility. As this project follows SemVer breaking changes are not only those which break compilation, but also those which break binary compatibility.

This feature doesn't require such a deep refactoring and multiple breaking changes.

Additionally the `*Setted` pattern has a huge drawback if the options are recreated from other media (database, JSON) which happens a lot if somebody uses the configuration import/export feature (I don't know about current moment but in past it was quite widely used feature).

**Comment by Vampire2008** [comment]
> The only way I see this functionality going in is the second option you have described (this is the one I've intended in my comment).

But it doubles work and control. It is not good. Developers needed to be change code in two places (C# and JavaScript).  Personaly, I don't want to do double work.
My option is independent of any pre-defined default values. If developers of JqGrid suddenly changed default values, my code will be work. Or if any developer uses some fork of JqGrid with different default values, my code will be work (if there aren't another breacking changes in fork of JqGrid).

Your code is completely based on pre-defined default values.
Maybe we should increase the major version number?

**Comment by tpeczek** [comment]
> But it doubles work and control. It is not good. Developers needed to be change code in two places (C# and JavaScript). Personaly, I don't want to do double work.
My option is independent of any pre-defined default values. If developers of JqGrid suddenly changed default values, my code will be work. Or if any developer uses some fork of JqGrid with different default values, my code will be work (if there aren't another breacking changes in fork of JqGrid).

I'm not saying your arguments are incorrect. I do understand that from your perspective this is the API which best fits the use case. What I'm saying is that my perspective is different. As a result of invested time, experience and conversations with users I my values hierarchy is a little bit different. This change doesn't bring that much value value and the need isn't high enough for me to justify such a ground rework. If I would be starting from scratch I would probably rethink a thing or two, but this is not the case and consistency is relevant.

**Comment by Vampire2008** [comment]
Ok. Than close this pull request.
I will leave my code for personal using.

**Comment by tpeczek** [comment]
Too bad, in proper form it would be a nice addition to the project 😞 .

**Comment by Vampire2008** [comment]
I don't have time and desire to do this. But you can do your option yourself.
I will try create pull request on other small changes.

**Pull request closed without merging**
