### PR TITLE
Now JqGrid support if you changing JqGrid default values in JavaScript.

### PR DESCRIPTION
**Pull request by Vampire2008**
Hello!
Some developers changing default values of JqGrid in JavaScript. 
Example:
```javascript
$.jqgid.default.cmTemplate = { align: 'center' };
```
And if deleloper wants to set aligment in one column to Left, with you library that doesn't work.
I did so that for every option JavaSctipt generetes only if option was setted. I did it for options in ColumnModel (and it dependensies) and JqGridOptions.

The truth is, there are disadvantages:
- If we set Editable, Searchable or Sortable attributes, JavaScript for this options always generates.
- JqGridHelper constructor with multiple parametres generate more redurant JavaScript code. I mark them as Obsolete. And create new constructor with JqGridOption as parameter.
- I changed behavior of JsonReader and ParameterNames. In static fields they uses only for Requests and Responses (global scope). In JqGridOption uses to set different than global values for Grid. And if we change something in JsonReader/ParametersNames in global scope, we need to change default values for JqGrid in JavaScript.

Other changes:
- Added Bootstrap 4 support and IconSets for it.
- In JqGridOptions added static field DefaultCompatibilityMode. If we use in whole project only Gurido JqGrid we don't need anymore define Compatibility mode for every grid.
- Seeding ColumnModel now in base JqGridOption class with method SetModel. Generic version of JqGridOption leaved for compatibility.
- For attributes Editable, Searchable removed bool parameter in constructors where we set additional fields. I decided if we sets this parameters, that that field is Editable/Searchable. In other constructors for bool value added default value.
- Added new fluent API method ExtendColumnOptions. That method gives us to some options that we can't set in attributes.
- Added support JetBrains.Annotations.

I broke one of the rules of contributing. I did many code refactoring (with support JetBrains Resharper):
- Removed unused usings.
- Changed variable declarations to var. (I like to using var in code)
- Changed code style to C# 7.2
- Changed spaces to tabs

### CODE REVIEW

**Comment by tpeczek** [comment]
Wow, this is a massive pull request. So first of all I appreciate your effort. There is a lot of good stuff in there.

That said, I don't see a way to accept this pull request as it is. It is simply to big, I'm not able to review/validate all the changes. Also there are some changes that I don't agree with. For example [Contributing Guidelines](https://github.com/tpeczek/Lib.Web.Mvc/blob/master/CONTRIBUTING.md) explictly state that code formatting should be maintained. I might like the some of the style changes (this is an old code to be honest), but I do prefer spaces over tabs and I'm strongly against `var` overuse.

If you are willing to submit this in a series of small pull requests (one per each change you propose) I will be more than happy to review and have discussion regarding every one of them

**Comment by Vampire2008** [comment]
I have returned spaces and removed vars.
Now review code will be easier.
Main change (default value) affects most of files. Other changes more smaller than main.

**Comment by tpeczek** [comment]
This is still way too big. One hundred of files, thousands of changes. I don't see a way to bring this in safely. Pull requests should be small, focused around single new or changed feature. This way they can be carefully reviewed and have meaningful discussion (if needed). You should also try to avoid unnecessary changes.

**Comment by tpeczek** [comment]
As we have moved to another pull request, I'm closing this one.

**Pull request closed without merging**
